name: aws-v5
on:
  push:
    branches:
      - main

# actions/setup-java@v2는 사용자 정의 배포를 지원하고 Zulu OpenJDK, Eclipse Temurin 및 Adopt OpenJDK를 기본적으로 지원합니다. v1은 Zulu OpenJDK만 지원합니다.
jobs:
  build: # 마음대로 적어도됨.
    runs-on: ubuntu-18.04   #실행 환경 (ubuntu 가 ci 에 설치됨)
    steps:                  #단계구분 - name 은 필수는 아님
      - name: Checkout
        uses: actions/checkout@v2    #actions/checkout@v2:  1) git init 2) git fetch or pull
      - name: Set up JDK 11
        uses: actions/setup-java@v1  #actions/setup-java@v1
        with:
          java-version: 11
      - name: Grant execute permission for gradlew
        run: chmod +x ./gradlew
        shell: bash
      - name: Build with Gradle
        run: ./gradlew clean build
        shell: bash
